export const jobsMocks = [
  {
    id: 1,
    owner: "augusto.alvarez.smith@gmail.com",
    worker: null,
    description:
      "Necesito ayuda para mover un sillón en la comuna de Las Condes",
    date: "On Sun, 3 Dec",
    dateType: 1,
    beforeDate: false,
    flexible: false,
    originalBudget: "20000",
    acceptedBudget: null,
    details: "Detalles lren itsum",
    online: "Remote",
    location: "Martin de Zamora, Las Condes, 4891",
    status: "Published",
    offers: 4,
  },
  {
    id: 2,
    owner: "augusto.alvarez.smith@gmail.com",
    worker: null,
    description:
      "Necesito que alguien pasee a mi perro los miércoles en la tarde",
    date: "On Sun, 3 Dec",
    dateType: 1,
    beforeDate: false,
    flexible: false,
    originalBudget: "20000",
    acceptedBudget: null,
    details: "Detalles lren itsum",
    online: "In Person",
    location: "Martin de Zamora, Las Condes, 4891",
    status: "Published",
    offers: 14,
  },
  {
    id: 3,
    owner: "augusto.alvarez.smith@gmail.com",
    worker: null,
    description: "Necesito 4 personas que repartan flyers en metro Tobalaba",
    date: "On Sun, 3 Dec",
    dateType: 1,
    beforeDate: false,
    flexible: false,
    originalBudget: "20000",
    acceptedBudget: null,
    details: "Detalles lren itsum",
    online: "In Person",
    location: "Martin de Zamora, Las Condes, 4891",
    status: "Closed",
    offers: 0,
  },
];
